const config = require('./config')
const { STORAGE_KEY } = require('./constants')

module.exports = async function (context, { categories }) {
  let categoryTree = unflatten(categories)

  // if there is only one category on route level, start one level further down in the tree
  if (categoryTree.length === 1) {
    categoryTree = categoryTree[0].children
  }

  await context.storage.extension.set(STORAGE_KEY, {
    categoryTree,
    created: Date.now()
  })

  return { categoryTree }
}

function unflatten (array, parent = { id: null }) {
  // Reverse sort order, if the response has been generated by the catalog service
  // In the product service the category with the highest sort index is shown first -> 353, 352, 351
  // In the catalog service the category with the lowest sort index is shown first -> 351, 352, 353
  let sortFunction
  if (config.useCatalogService) {
    sortFunction = (a, b) => parseInt(a.sort) - parseInt(b.sort)
  } else {
    sortFunction = (a, b) => parseInt(b.sort) - parseInt(a.sort)
  }

  const children = array
    .filter((child) => child.parent.id === parent.id)
    .sort(sortFunction)

  if (!children.length) {
    return []
  }

  let tree = []

  if (parent.id === null) {
    tree = children
  } else {
    parent['children'] = children
  }

  children.forEach((child) => unflatten(array, child))

  return tree
}
